<?php

namespace Rosiumdata\Laravel\Support;

use Rosiumdata\Laravel\ActionColumn;
use Rosiumdata\Laravel\Column;
use Rosiumdata\Laravel\RosiumTable;
use Rosiumdata\Laravel\RosiumdataServiceProvider;

class JsGenerator
{
    /**
     * Generate the JS file for a single table class.
     */
    public function generate(string $tableClass): string
    {
        if (!class_exists($tableClass)) {
            throw new \InvalidArgumentException("Class [{$tableClass}] does not exist.");
        }

        /** @var RosiumTable $instance */
        $instance = new $tableClass;

        $columns = array_map(fn ($col) => $col->toArray(), $instance->columns());
        $columnsJson = json_encode(
            $columns,
            JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES
        );

        $name = $instance::name();
        $pageSize = $instance->defaultPageSize();
        $locale = $instance->locale();
        $persistence = $instance->persistenceKey();
        $eventHandlers = $instance->eventHandlers();

        $persistenceLine = $persistence
            ? "\n  el.persistence = '{$persistence}'"
            : '';

        $eventHandlersBlock = $eventHandlers
            ? "\n\n{$eventHandlers}"
            : '';

        $route = $this->routePrefix() . '/' . $name;

        return <<<JS
import { LaravelAdapter } from '@rosiumdata/core'

export function init{$name}Table() {
  const el = document.querySelector('rosium-table[rosium="{$name}"]')
  if (!el) return

  el.columns = {$columnsJson}
  el.pageSize = {$pageSize}
  el.locale = '{$locale}'{$persistenceLine}
  el.adapter = new LaravelAdapter('/{$route}', {
    headers: { 'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]')?.content ?? '' }
  }){$eventHandlersBlock}
}

JS;
    }

    /**
     * Generate JS files for all registered tables.
     * Only writes files when content has actually changed — avoids
     * triggering Vite HMR / page reload on every request.
     */
    public function generateAll(): void
    {
        $jsPath = $this->jsPath();

        if (!is_dir($jsPath)) {
            mkdir($jsPath, 0755, true);
        }

        foreach (RosiumdataServiceProvider::tables() as $class) {
            $name = $class::name();
            $js = $this->generate($class);
            $this->writeIfChanged("{$jsPath}/{$name}.js", $js);
        }

        $initContent = $this->generateInit(RosiumdataServiceProvider::tables());
        $this->writeIfChanged($this->initPath(), $initContent);
    }

    /**
     * Generate the rosium-init.js that imports and initializes all tables.
     *
     * @param array<int, class-string<RosiumTable>> $tableClasses
     */
    public function generateInit(array $tableClasses): string
    {
        $imports = '';
        $calls = '';

        $jsPath = $this->jsPath();
        $initDir = dirname($this->initPath());

        foreach ($tableClasses as $class) {
            if (!class_exists($class)) {
                continue;
            }
            $name = $class::name();
            $tableFile = "{$jsPath}/{$name}.js";
            $relativePath = $this->relativePath($initDir, $tableFile);
            $imports .= "import { init{$name}Table } from '{$relativePath}'\n";
            $calls .= "init{$name}Table()\n";
        }

        return <<<JS
// Auto-generated by RosiumData. Do not edit manually.
import '@rosiumdata/vanilla'
import '@rosiumdata/vanilla/theme/default.css'
{$imports}
{$calls}
JS;
    }

    /**
     * Compute a relative path from $from (directory) to $to (file).
     * Falls back to ./rosium/file.js when paths share the resource root.
     */
    private function relativePath(string $fromDir, string $toFile): string
    {
        $from = rtrim($fromDir, '/');
        $to = $toFile;

        // Same directory: ./file.js
        if (dirname($to) === $from) {
            return './' . basename($to);
        }

        // Try to build a relative path.
        $fromParts = explode('/', $from);
        $toParts = explode('/', $to);

        $common = 0;
        $max = min(count($fromParts), count($toParts));
        for ($i = 0; $i < $max; $i++) {
            if ($fromParts[$i] === $toParts[$i]) {
                $common++;
            } else {
                break;
            }
        }

        if ($common === 0) {
            return './' . ltrim($to, '/');
        }

        $up = str_repeat('../', count($fromParts) - $common);
        $down = implode('/', array_slice($toParts, $common));
        $result = $up . $down;

        // ES modules require ./ or ../ for relative imports
        if (!str_starts_with($result, '.') && !str_starts_with($result, '/')) {
            $result = './' . $result;
        }

        return $result;
    }

    private function routePrefix(): string
    {
        return config('rosiumdata.route_prefix', 'rosium-data');
    }

    private function jsPath(): string
    {
        return config('rosiumdata.js_path', resource_path('js/rosium'));
    }

    private function initPath(): string
    {
        return config('rosiumdata.init_path', resource_path('js/rosium-init.js'));
    }

    private function writeIfChanged(string $path, string $content): void
    {
        $existing = is_file($path) ? file_get_contents($path) : null;

        if ($existing !== $content) {
            $tmp = $path . '.tmp.' . getmypid();
            file_put_contents($tmp, $content);
            rename($tmp, $path);
        }
    }
}
